Infomaniak/android-SwissTransfer

app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/MainScaffold.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/sent/SentScreen.kt

core: Share navtype with a compose provider

---

app/src/main/java/com/infomaniak/swisstransfer/ui/icons/AppIcons.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/icons/app/ArrowDownCircle.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/icons/app/ArrowUpCircle.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/icons/app/Settings.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/navigation/NavigationItem.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

Adds first icons and string ressources by the same occasion
Depends on #11

Use correct strings and icon values for the bottom nav bar

---

app/build.gradle.kts
app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwissTransferFab.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/icons/AppIcons.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/icons/illu/ArrowCurvedDownright.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/sent/SentScreen.kt
gradle/libs.versions.toml

Also adds the constraint layout compose dependency for this extreme case
Depends on #16

Add the arrow to the empty state new transfer fab

---

app/src/main/java/com/infomaniak/swisstransfer/ui/icons/AppIcons.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/icons/app/Add.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/icons/app/ArrowDownCircle.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/icons/app/ArrowUpCircle.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/icons/app/Settings.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/icons/illu/ArrowCurvedDownright.kt

Use a variable to centralize the icon preview sizes

---

app/src/main/java/com/infomaniak/swisstransfer/ui/components/BottomSheetItem.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/LargeButton.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwissTransferBottomSheet.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/icons/app/Camera.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/icons/app/Folder.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/icons/app/PolaroidLandscape.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/MainScaffold.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/theme/ColorDark.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/theme/ColorLight.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/theme/CustomShapes.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/theme/Shapes.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/theme/Theme.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

Add bottom sheet items component and use them in transfer upload source choice bottom sheet

---

app/src/main/java/com/infomaniak/swisstransfer/ui/components/LargeButton.kt

Fix LargeButtons

---

app/src/main/java/com/infomaniak/swisstransfer/extensions/ContextExt.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsScreen.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

depends on https://github.com/Infomaniak/android-SwissTransfer/pull/32

Implement external settings links

---

app/src/main/java/com/infomaniak/swisstransfer/ui/components/BottomStickyButtonScaffold.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/Buttons.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/DoubleButtonCombo.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/TwoPaneScaffold.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/navigation/NavigationDestination.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/MainNavHost.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/MainScaffold.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/MainScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/sent/SentScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsDownloadsLimitScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsScreenWrapper.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsThemeScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/components/SettingItem.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/components/SingleSelectOptions.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/NewTransferNavHost.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/TransferTypeScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/components/TransferTypeButtons.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/theme/Theme.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/theme/Type.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/utils/ContextExt.kt

Format code

---

app/src/main/java/com/infomaniak/swisstransfer/ui/icons/app/Add.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/icons/app/ArrowDownCircle.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/icons/app/ArrowLeft.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/icons/app/ArrowUpCircle.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/icons/app/Bell.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/icons/app/BlackAndWhiteCircle.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/icons/app/BlackCircle.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/icons/app/Camera.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/icons/app/Checkmark.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/icons/app/ChevronRightSmall.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/icons/app/Clock.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/icons/app/Cross.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/icons/app/FileBadgeArrowDown.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/icons/app/Folder.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/icons/app/OpenOutside.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/icons/app/PaintbrushPalette.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/icons/app/PolaroidLandscape.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/icons/app/Settings.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/icons/app/SpeechBubble.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/icons/app/WhiteCircle.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/icons/illu/ArrowCurvedDownright.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/icons/illu/ChainTilted.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/icons/illu/EnvelopeTilted.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/icons/illu/LogoInfomaniak.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/icons/illu/LogoSwissTransfer.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/icons/illu/QrCodeTilted.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/icons/illu/WaveSignalTilted.kt

Same modifications for all files.

Clean Icons & Illustrations code

---

app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwissTransferBottomSheet.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/ArrowDownFile.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/ArrowOpenOutside.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/CircleBlack.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/CircleBlackAndWhite.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/CircleWhite.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/ArrowDownRightCurved.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/sent/SentScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsThemeScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/components/SettingItem.kt

Rename some Images

---

app/src/main/java/com/infomaniak/swisstransfer/ui/components/EmptyState.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/ArrowRightCurved.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/MascotSearching.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/received/ReceivedScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/received/components/ReceivedEmptyFab.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/sent/SentEmptyScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/sent/SentScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/theme/Dimens.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/theme/Margin.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

Add empty ReceivedScreen

---

app/src/main/java/com/infomaniak/swisstransfer/ui/components/NewTransferFab.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/UploadSourceChoiceBottomSheet.kt

Display UploadSourceChoiceBottomSheet before navigating to NewTransferScreen

---

app/src/main/java/com/infomaniak/swisstransfer/ui/components/NewTransferFab.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/UploadSourceChoiceBottomSheet.kt

This reverts commit 7067323ac37ed3cb90d028349e1d03c5fc4d8b2b.

Revert "Display UploadSourceChoiceBottomSheet before navigating to NewTransferScreen"

---

app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt

Automatically display UploadSourceChoiceBottomSheet when opening ImportFilesScreen

---

app/src/main/java/com/infomaniak/swisstransfer/ui/components/NewTransferFab.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/sent/SentEmptyScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/UploadSourceChoiceBottomSheet.kt

Clean code

---

app/src/main/java/com/infomaniak/swisstransfer/ui/components/BrandTobAppBar.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwissTransferTobAppBar.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/MainScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/components/BrandTobAppBarScaffold.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/components/MainScaffold.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/components/SmallWindowTopAppBarScaffold.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/received/ReceivedScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/sent/SentEmptyScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/sent/SentListScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/sent/SentScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsDownloadsLimitScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsEmailLanguageScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsScreenWrapper.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsThemeScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsValidityPeriodScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/components/OptionScaffold.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/NewTransferScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/TransferTypeScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/UploadSourceChoiceBottomSheet.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/utils/MultiplePreview.kt

Rename Phone/Mobile into SmallWindow & Tablet into LargeWindow

---

app/src/main/java/com/infomaniak/swisstransfer/ui/components/BrandTopAppBar.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/MainScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/components/BrandTopAppBarScaffold.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/components/MainScaffold.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/received/ReceivedScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/sent/SentScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsScreen.kt

Rename `BrandTobAppBar` into `BrandTopAppBar`

---

app/src/main/java/com/infomaniak/swisstransfer/ui/MainActivity.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsScreenWrapper.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/theme/Theme.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/utils/GetSetCallbacks.kt

https://github.com/user-attachments/assets/ddd2959b-204e-4eda-a3a8-d81057e0b426

Use theme stored in realm

---

app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

feat: Add strings related to Data Management

---

app/src/main/java/com/infomaniak/swisstransfer/ui/images/ThemedImage.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/matomo/Matomo.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/matomo/MatomoDark.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/matomo/MatomoLight.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/sentry/Sentry.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/sentry/SentryDark.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/sentry/SentryLight.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/dataProtection/DataProtection.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/dataProtection/DataProtectionDark.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/dataProtection/DataProtectionLight.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/matomo/Matomo.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/matomo/MatomoDark.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/matomo/MatomoLight.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/sentry/Sentry.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/sentry/SentryDark.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/sentry/SentryLight.kt

feat: Add images related to Data Management

---

app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/dataProtection/DataProtectionDark.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/dataProtection/DataProtectionLight.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/uploadSuccessEmail/UploadSuccessEmail.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/uploadSuccessEmail/UploadSuccessEmailDark.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/uploadSuccessEmail/UploadSuccessEmailLight.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/uploadSuccessQr/UploadSuccessQr.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/uploadSuccessQr/UploadSuccessQrDark.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/uploadSuccessQr/UploadSuccessQrLight.kt

feat: Add UploadSuccess Email & QR illustrations

---

app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

feat: Add strings related to UploadSuccess feature

---

app/src/main/java/com/infomaniak/swisstransfer/ui/components/Buttons.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt

Needed in a future PR, but the component modification is handled in its own PR here

Add loader inside buttons

---

app/src/main/java/com/infomaniak/swisstransfer/ui/components/BrandTopAppBar.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/Buttons.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/CrossCircleButton.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/FileItem.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/IllustratedMessageBlock.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/received/components/ReceivedEmptyFab.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/sent/SentEmptyScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/components/ImportedFilesCard.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/components/TransferTypeButton.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/components/TransferTypeButtons.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadSuccessEmailScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadSuccessQrScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/theme/Margin.kt

Rename margins to the new standard shared with iOS

---

app/src/main/java/com/infomaniak/swisstransfer/ui/components/FileItem.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/FileItemList.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/FilePreview.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/SmallFileItem.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/previewparameter/FileUiListPreviewParameterProvider.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/received/ReceivedScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/sent/SentListScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/FilesMutableStateFlow.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/ImportationFilesManager.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/components/ImportedFilesCard.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/utils/FileUiItemExt.kt

Two properties had to change name to adapt to the KMP model but apart from this, the replacement was straight forward

Replace local FileUi data class with KMP FileUi model

---

gradle/libs.versions.toml

Bump ST KMP version

---

Core2/src/main/java/com/infomaniak/core2/DateUtils.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/EmptyState.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/FileItem.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwissTransferBottomSheet.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/TextDotText.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/transfer/TransferExpiredBottomSheet.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/transfer/TransferItem.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/Bin.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/mascotDead/MascotDead.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/mascotDead/MascotDeadDark.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/mascotDead/MascotDeadLight.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/received/ReceivedScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/UploadSourceChoiceBottomSheet.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/utils/HumanReadableSizeUtils.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

Expired transfer BottomSheet

---

app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/NewTransferNavHost.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadProgressScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadProgressViewModel.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/components/UploadProgressScreen.kt

Connect upload back and UI

---

app/src/main/java/com/infomaniak/swisstransfer/ui/MatomoSwissTransfer.kt

No need for the MainActivity cast

Fix crash of new transfer activity

---

app/src/main/java/com/infomaniak/swisstransfer/ui/navigation/NavigationDestination.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/MainNavHost.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/received/ReceivedScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/received/ReceivedScreenWrapper.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/sent/SentScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsScreenWrapper.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/TransferDetailsScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/utils/ScreenWrapperUtils.kt

Use a TwoPaneScaffold for ReceivedScreen

---

app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsDownloadsLimitScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsEmailLanguageScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsValidityPeriodScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsViewModel.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/NewTransferViewModel.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/TransferOptionsBottomSheets.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ValidityPeriodOptionBottomSheet.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/components/TransferAdvancedSetting.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/components/TransferAdvancedSettings.kt

Depends on #142 
The password option is useless in this PR, but as it's not mandatory for a first working alpha, It will be developped it in a later PR

feat: Add advanced option buttons states

---

Core2/src/main/res/values-de/strings.xml
Core2/src/main/res/values-es/strings.xml
Core2/src/main/res/values-fr/strings.xml
Core2/src/main/res/values-it/strings.xml
Core2/src/main/res/values/strings.xml
app/src/main/java/com/infomaniak/swisstransfer/ui/components/EmptyState.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/transfer/TransferExpiredBottomSheet.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/uploadError/GhostMagnifyingGlassQuestionMark.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/uploadError/GhostMagnifyingGlassQuestionMarkDark.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/uploadError/GhostMagnifyingGlassQuestionMarkLight.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/navigation/NavigationDestination.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/received/ReceivedScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/NewTransferNavHost.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadErrorScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadProgressScreen.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

Add the upload error screen without using it yet. Using it can either come in another PR after @sirambd 's one is merged or directly in this one if it is deemed more adapted

Add upload error screen

---

app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsDownloadsLimitScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsEmailLanguageScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsValidityPeriodScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/ImportFilesViewModel.kt

The password is still missing for now. Also the message has not been connected yet either

Connect first advanced settings to upload api call

---

app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwissTransferAlertDialog.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwissTransferTextField.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwissTransferTopAppBar.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/TransferDetailsScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/TransferDetailsViewModel.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/components/PasswordBottomSheet.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/components/QrCodeBottomSheet.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transfers/TransfersScreenWrapper.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transfers/TransfersViewModel.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadProgressScreen.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

feat: Display sent Transfers details

---

app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt

revert ccf96983cd342e881ef219a2724476c37fca7921

chore: Put back password option to avoid crash

---

FileTypes/src/main/java/com/infomaniak/library/filetypes/FileType.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/ImportationFilesManager.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/utils/FileUiExt.kt

Before:
https://github.com/user-attachments/assets/14f7ffb0-d0c9-4b50-bbc6-49ca22a9f621
After:
https://github.com/user-attachments/assets/a50175ed-1641-4766-b949-77ae9cd5eb98

fix: Put the correct mimeType when importing files

---

app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/components/AppNavigationSuiteScaffold.kt

Adds label to navigation rail to make icons clearer and this style stays coherent with material 3

feat: Improve NavigationRail by adding label

---

app/src/main/java/com/infomaniak/swisstransfer/ui/MainApplication.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/utils/TransferUiExt.kt

feat: Auto-delete old expired Transfers

---

app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwissTransferButton.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/transfer/TransferFilePreview.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/TransferDetailsScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/ImportFilesViewModel.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
app/src/main/res/drawable/splashscreen_legacy.xml

refactor: Clean code

---

app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/TransferDetailsScreen.kt

fix: Better BottomBar button spacing for all languages

---

app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/ImportFilesViewModel.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

feat: Make sure Transfer author email is mandatory and correctly formatted

---

app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

The string has been update in the specs to remove the redundant "…" with the message right above it

refactor: Update networkUnavailable string

---

app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/ImportFilesViewModel.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/workers/UploadWorker.kt

https://github.com/user-attachments/assets/68fb0b71-5089-43f8-a0cd-fde476fc1427

fix: Call init of UploadSession outside of worker to handle email verification easily

---

app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/ImportFilesViewModel.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/TransferSendManager.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt

I will need to call this code again in another screen's view model so I needed to extract this to make it reusable

feat: Factorize send transfer logic to a reusable class

---

Core2/build.gradle.kts
Core2/gradle/core2.versions.toml
Core2/src/main/java/com/infomaniak/core2/DownloadManagerUtils.kt
Core2/src/main/java/com/infomaniak/core2/extensions/PackageManager.kt
Core2/src/main/res/values-de/strings.xml
Core2/src/main/res/values-es/strings.xml
Core2/src/main/res/values-fr/strings.xml
Core2/src/main/res/values-it/strings.xml
Core2/src/main/res/values/strings.xml
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/TransferDetailsScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/TransferDetailsViewModel.kt

Before this PR, the button was no-op.

feat: Make the download button download all files

---

Core2/AppIntegrity/src/main/java/com/infomaniak/core2/appintegrity/AppIntegrityManager.kt
Core2/AppIntegrity/src/main/java/com/infomaniak/core2/appintegrity/AppIntegrityRepository.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/ImportFilesViewModel.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/TransferSendManager.kt

feat: Add `resendLastTransfer()` function in TransferSend manager

---

app/src/main/java/com/infomaniak/swisstransfer/ui/components/EmptyState.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/IllustratedMessageBlock.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/NewTransferFab.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/QrCode.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwissTransferBottomSheet.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwissTransferChips.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwissTransferFab.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/onboarding/RadialGradientCornerTopLeft.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/onboarding/RadialGradientCornerTopRight.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/onboarding/StorageCardboardBoxPile.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/onboarding/ThreeCardsTransferType.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/onboarding/TwoLocksIntertwinedStars.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/uploadAd/MetallicSafe.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/uploadAd/MountainGondola.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/uploadAd/SwissWithFlag.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/uploadCancelBottomSheet/RedCrossPaperPlanes.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/uploadError/GhostMagnifyingGlassQuestionMark.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadProgressScreen.kt

style: Use `@PreviewLightAndDark` everywhere it's needed

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/infomaniak/swisstransfer/ui/utils/ContextExt.kt

feat: List two more apps in the "open mail app" button

---

Core2/AppIntegrity/src/main/java/com/infomaniak/core2/appintegrity/AppIntegrityManager.kt
Core2/Matomo/build.gradle.kts
Core2/Matomo/src/main/java/com/infomaniak/core2/matomo/Matomo.kt
Core2/Network/build.gradle.kts
Core2/Network/src/main/java/com/infomaniak/core2/network/NetworkAvailability.kt
Core2/Onboarding/build.gradle.kts
Core2/Onboarding/src/main/java/com/infomaniak/core2/onboarding/HorizontalPagerIndicator.kt
Core2/Onboarding/src/main/java/com/infomaniak/core2/onboarding/OnboardingScaffold.kt
Core2/Sentry/build.gradle.kts
Core2/Sentry/src/main/java/com/infomaniak/core2/sentry/SentryLog.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/LaunchActivity.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/MatomoSwissTransfer.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/navigation/NavigationDestination.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/TransferDetailsViewModel.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transfers/TransfersViewModel.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/ImportFilesViewModel.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/ImportLocalStorage.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/ImportationFilesManager.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/TransferSendManager.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadProgressViewModel.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/onboarding/OnboardingScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/workers/UploadFileTask.kt
app/src/main/java/com/infomaniak/swisstransfer/workers/UploadWorker.kt

refactor: Move Core2 modules to correct packages

---

app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwissTransferTopAppBar.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsDataManagementMatomoScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsDataManagementScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsDataManagementSentryScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/components/OptionScaffold.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/TransferDetailsScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/validateemail/ValidateUserEmailScreen.kt

This will bring more flexibility for the content

chore: Make SwissTransferTopAppBar composition friendly

---

app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/TransferSendManager.kt

IntegrityException and EmailValidationRequired are expected to happen and should not spam sentry. I simplified the code to only report interesting issues

fix: Do not report to sentry known errors that are expected to happen

---

app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwissTransferChips.kt

The style of chips has been officially update to the material 3 style in the spec. This PR applies the update

feat: Update chip style to material 3

---

app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/TransferDetailsScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/TransferDetailsViewModel.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/components/PasswordAlertDialogs.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/components/PasswordOptionAlertDialog.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml
gradle/libs.versions.toml

Add the possibility to open a password-protected deeplink.

feat: Password deeplink

---

app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/TransferDetailsViewModel.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml
gradle/libs.versions.toml

Depends on https://github.com/Infomaniak/multiplatform-SwissTransfer/pull/137
Need release of ST 0.11.0

feat: Display a Toast when we try to add an expired transfer via a deeplink

---

app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/TransferDetailsViewModel.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml
gradle/libs.versions.toml

Depends on https://github.com/Infomaniak/multiplatform-SwissTransfer/pull/148

chore: Update deeplink exception for expired deeplinks

---

app/src/main/java/com/infomaniak/swisstransfer/ui/navigation/NavigationDestination.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/ImportFilesViewModel.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/NewTransferNavHost.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/components/EmailAddressTextField.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadProgressScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadSuccessEmailScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadSuccessScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadSuccessViewModel.kt
app/src/main/java/com/infomaniak/swisstransfer/workers/UploadWorker.kt

Depends on https://github.com/Infomaniak/multiplatform-SwissTransfer/pull/145

refactor: Remove `recipients` from navigation

---

Core2/Compose/Basics/build.gradle.kts
Core2/Compose/Basics/src/main/java/com/infomaniak/core2/compose/basics/CallableState.kt
Core2/Compose/Basics/src/main/java/com/infomaniak/core2/compose/basics/FlowForwarding.kt
Core2/build.gradle.kts
Core2/gradle/core2.versions.toml
Core2/src/main/java/com/infomaniak/core2/AutoCancelScope.kt
Core2/src/main/java/com/infomaniak/core2/DownloadManager.kt
Core2/src/main/java/com/infomaniak/core2/DownloadManagerUtils.kt
Core2/src/main/java/com/infomaniak/core2/HumanReadableErrors.kt
Core2/src/main/java/com/infomaniak/core2/Lifecycle.kt
Core2/src/main/java/com/infomaniak/core2/Uri.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwissTransferTopAppBar.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/Stop.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/components/SwissTransferScaffold.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/TransferDetailsScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/TransferDetailsViewModel.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/TransferDownload.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/TransferDownloadComposeUi.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/TransferDownloadUi.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/utils/ContextExt.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

- Follow progress and display it to the user
- Connect back to the system's DownloadManager
- Allow cancelling the download
- Allow opening the download
- Tell the user if an error happens while downloading
- Automatically detect if the file is deleted externally

feat: Show transfer download status live

---

Core2/Notifications/src/main/java/com/infomaniak/core2/notifications/NotificationsUtilsCore.kt
Core2/src/main/java/com/infomaniak/core2/NumberUtils.kt
app/src/main/AndroidManifest.xml
app/src/main/java/com/infomaniak/swisstransfer/di/ApplicationModule.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/MainApplication.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/NewTransferActivity.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/navigation/NotificationNavigation.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/NewTransferNavHost.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/NewTransferScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadProgressScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadSuccessScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/components/Progress.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/utils/NotificationsUtils.kt
app/src/main/java/com/infomaniak/swisstransfer/workers/UploadWorker.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

Depends on #330
Depends on #331
Depends on #334

feat: Add Upload progress & success notifications

---

app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadErrorScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadProgressScreen.kt

fix: Disable back in UploadError screen

---

Core2/src/main/java/com/infomaniak/core2/DownloadManagerUtils.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/FileItem.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/FileItemList.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/transfer/FilesDetailsScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/TransferDetailsScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/TransferDownload.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/TransferDownloadComposeUi.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/components/FilesDetailsScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/filesdetails/NewTransferFilesDetailsScreen.kt

feat: Per file download + open

---

app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/ImportFilesViewModel.kt

When the activity is killed and recreated, remember to not handle `NewTransferOpenManager.Reason.Other` thanks to `isFirstViewModelCreation`

fix: Do not display file picker when the activity is killed and recreated if it's not needed

---

app/src/main/java/com/infomaniak/swisstransfer/ui/NewTransferActivity.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/navigation/NotificationNavigation.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/NewTransferNavHost.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/NewTransferScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/NewTransferViewModel.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadErrorScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadProgressScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/utils/NotificationsUtils.kt
app/src/main/java/com/infomaniak/swisstransfer/workers/UploadWorker.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

feat: Add Upload failure notification

---

app/src/main/java/com/infomaniak/swisstransfer/ui/components/FileItemList.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/transfer/FilesDetailsScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/TransferDetailsScreen.kt

https://github.com/user-attachments/assets/ea2b38af-49dd-4a90-bce4-7972db491147

fix: Hide download button if we are in the FilesDetailsScreen

---

app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/onboarding/StorageCardboardBoxPileDark.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/onboarding/StorageCardboardBoxPileLight.kt

The spec has changed, I updated the illustration to the new version

chore: Update onboarding cardboard box pile illustration to the new version

---

app/src/main/java/com/infomaniak/swisstransfer/ui/MainActivity.kt
gradle/libs.versions.toml

Update all the transfers att the start of the mainActivity, but at most once per 15min

feat: Refresh transfer list

---

.gitignore
build.gradle.kts
settings.gradle.kts

Depends on https://github.com/Infomaniak/android-core/pull/256
Depends on https://github.com/Infomaniak/android-core/pull/257

refactor: Remove `app` dependency in `Core`

---

app/src/main/java/com/infomaniak/swisstransfer/ui/navigation/NavigationDestination.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/MainNavHost.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/MainScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/components/MainScaffold.kt

Remove blink when navigating on Sent screen 
Before :
https://github.com/user-attachments/assets/82d8edc8-8649-4380-a228-154ad20cfd0e

feat: Disable transition on 'MainNavHost'

---

app/build.gradle.kts
app/src/main/AndroidManifest.xml
app/src/main/java/com/infomaniak/swisstransfer/ui/components/FileItemList.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/transfer/FilesDetailsScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/TransferDetailsScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/TransferDownloadComposeUi.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/utils/PermissionsUtils.kt
gradle/libs.versions.toml

feat: Check write permission for API <= 28

---

app/src/main/java/com/infomaniak/swisstransfer/ui/components/FileItemList.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/TransferDetailsScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/TransferDownloadComposeUi.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/utils/PermissionsUtils.kt

feat: Remember user intent after permission grant

---

app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/Shield.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsScreen.kt

feat: Add missing shield icon in data management setting

---

app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

iOS updated the strings to fix some wording in german, this PR updates the strings on Android after the corrections. The ink detection has also been update to try and detect usages of Überweisung/Überweisen

chore: Update strings mainly for german wording corrections

---

app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/components/AdHeader.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/theme/Type.kt

To make it stand out more, update the size of the font

feat: Update ad screen font size from 18sp to 20sp

---

app/src/main/java/com/infomaniak/swisstransfer/workers/FileChunkSizeManager.kt
app/src/main/java/com/infomaniak/swisstransfer/workers/UploadFileTask.kt

We've already had cases where the upload didn't go well and we got a 500 from the api.
After observation, when the last chunk didn't go last, we get errors with the api, so we make sure that the last chunk always goes last.

feat: Improved upload to avoid problems with api

---

app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/received/ReceivedScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/sent/SentScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/TransferDetailsScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transfers/TransfersScreenWrapper.kt

Before fix:
https://github.com/user-attachments/assets/55db53af-1071-4067-a24e-fc177422b725
After fix:
https://github.com/user-attachments/assets/01fc2c90-c258-46ed-8259-76749a38e229

fix: Transfer is deleted without creating a new one in the received tab and we display the empty state when we delete a transfer

---

app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/TransferSendManager.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadProgressScreen.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

Depends on #433
Depends on #435

feat: Block transfers originating from a restricted location

---

app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/TransferDownloadComposeUi.kt

Fixes SWISSTRANSFER-ANDROID-41

fix(StatusProgress): Fix a crash occurring because of a division by 0

---

app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsScreenWrapper.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transfers/TransfersScreenWrapper.kt

Depends on https://github.com/Infomaniak/android-core/pull/302

feat: Open PlayStore when clicking `Give your opinion` in Settings

---

app/src/main/java/com/infomaniak/swisstransfer/ui/MainApplication.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/FileItem.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/FileItemList.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/FilePreview.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/transfer/FilesDetailsScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/TransferDetailsScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/TransferDetailsViewModel.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/TransferManagerExt.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/components/ExistingTransferFilesDetailsScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/ThumbnailsLocalStorage.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/filesdetails/FilesDetailsViewModel.kt
app/src/main/java/com/infomaniak/swisstransfer/upload/TransferUploader.kt
app/src/main/java/com/infomaniak/swisstransfer/upload/UploadForegroundService.kt

depends on https://github.com/Infomaniak/multiplatform-SwissTransfer/pull/183

fix: Thumbnails are now generated with the copy free upload

---

app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/TransferDetailsViewModel.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transfers/TransfersViewModel.kt

Depends on https://github.com/Infomaniak/android-core/pull/313

fix: Rethrow CancellationException in AppIntegrity

---

app/src/main/java/com/infomaniak/swisstransfer/ui/components/TextDotText.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/transfer/TransferItem.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/components/TransferInfo.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/filesdetails/components/FilesSize.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/pickfiles/PickFilesScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/pickfiles/PickFilesViewModel.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/pickfiles/components/ImportedFilesCard.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/utils/HumanReadableSizeUtils.kt
app/src/main/java/com/infomaniak/swisstransfer/upload/UploadSessionManager.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml
gradle/libs.versions.toml

This PR implements the 5K & 50GiB file limits at the UI level.

feat: Implement file limits

---

app/src/main/java/com/infomaniak/swisstransfer/ui/LaunchActivity.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/matomo/MatomoDark.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/matomo/MatomoLight.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/beers/BeersDark.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/beers/BeersLight.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/dataProtection/DataProtectionDark.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/dataProtection/DataProtectionLight.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/mascotDead/MascotDeadDark.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/mascotDead/MascotDeadLight.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/mascotSearching/MascotSearchingDark.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/mascotSearching/MascotSearchingLight.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/matomo/MatomoDark.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/matomo/MatomoLight.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/AlreadyUsedFileNamesSet.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/pickfiles/PickFilesViewModel.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/pickfiles/components/ImportedFilesCard.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadFailureScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadViewModel.kt
app/src/main/java/com/infomaniak/swisstransfer/upload/AbandonedTransferCleanupWorker.kt
app/src/main/java/com/infomaniak/swisstransfer/upload/PickedFilesExtractorImpl.kt

depends on https://github.com/Infomaniak/android-SwissTransfer/pull/486

chore: Clean code

---

gradle/libs.versions.toml

Depends on https://github.com/Infomaniak/android-core/pull/341

chore: Bump Libs

---

app/build.gradle.kts

Build was blocked by missing sentryAuthToken when not provided even though it's only useful for release build but not for debug build

fix: Don't require sentryAuthToken if building for debug

---

.github/workflows/android.yml
app/build.gradle.kts
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transfers/TransfersGroupingManager.kt
app/src/main/res/values-fr/strings.xml
app/src/test/java/com/infomaniak/swisstransfer/TransferSectionGroupingTest.kt

depends on https://github.com/Infomaniak/android-SwissTransfer/pull/494

chore: Fix duplicate sections

---

app/src/main/java/com/infomaniak/swisstransfer/ui/OnboardingActivity.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/TransferDetailsScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/utils/ContextExt.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/utils/HumanReadableSizeUtils.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/utils/NotificationPermissionUtils.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/utils/NotificationsUtils.kt
build.gradle.kts

Depends on https://github.com/Infomaniak/android-core/pull/344
Depends on https://github.com/Infomaniak/android-core/pull/352

refactor: Bump SwissTransfer to minSdk 24

---

app/src/main/java/com/infomaniak/swisstransfer/ui/MainApplication.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transfers/TransfersGroupingManager.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transfers/TransfersViewModel.kt
gradle/libs.versions.toml

Depends on https://github.com/Infomaniak/multiplatform-SwissTransfer/pull/205
Depends on #499

feat: Order expired Transfers to the end of the lists

---

app/src/main/java/com/infomaniak/swisstransfer/di/CrashReportImpl.kt
gradle/libs.versions.toml

depends on https://github.com/Infomaniak/multiplatform-SwissTransfer/pull/207

fix: Update CrashReport interface with a message

---

app/src/main/java/com/infomaniak/swisstransfer/ui/MainActivity.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/DeeplinkViewModel.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transfers/components/DeleteTransferDialog.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/utils/DeeplinkExt.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml
gradle/libs.versions.toml

https://github.com/user-attachments/assets/529d9bf4-1626-4756-bcfa-09c49f415383

feat: Add a dialog to be able to delete a transfer if when we click on a delete deeplink

---

app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/pickfiles/components/EmailAddressTextField.kt

Automatically add in a chip the first text that is a valid email found in the clipboard when the user try to paste.

feat: Auto add first pasted text that is a valid email

---

gradle/libs.versions.toml

Depends on https://github.com/Infomaniak/android-core/pull/394

chore: Bump Core

---

app/src/main/java/com/infomaniak/swisstransfer/ui/utils/ContextExt.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/utils/NotificationsUtils.kt
build.gradle.kts

depends on https://github.com/Infomaniak/android-core/pull/403

chore: Bump minSDK from 24 to 27

---

app/build.gradle.kts
gradle/libs.versions.toml

Depends on https://github.com/Infomaniak/android-core/pull/421

chore: Bump Libs & Core

---

app/src/main/java/com/infomaniak/swisstransfer/ui/MatomoSwissTransfer.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/FileItemList.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/transfer/FilesDetailsScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/received/ReceivedScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/sent/SentScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsDownloadsLimitScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsEmailLanguageScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsThemeScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsValidityPeriodScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/components/OptionScaffold.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/TransferDetailsScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/TransferDetailsViewModel.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/TransferDownload.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/TransferDownloadComposeUi.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/components/ExistingTransferFilesDetailsScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transfers/TransfersScreenWrapper.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/filesdetails/FilesDetailsViewModel.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/filesdetails/NewTransferFilesDetailsScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/pickfiles/PickFilesScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/pickfiles/TransferOptionsBottomSheets.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/pickfiles/components/PasswordAlertDialogs.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/pickfiles/components/TransferTypeButtons.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadFailureScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadProgressScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadRetryScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadSuccessScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/components/ShareAndCopyButtons.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/validateemail/ValidateUserEmailScreen.kt
gradle/libs.versions.toml

Depends on [#213](https://github.com/Infomaniak/multiplatform-SwissTransfer/pull/213)

refactor: Matomo clean

---

app/build.gradle.kts
app/src/main/AndroidManifest.xml
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/onboarding/OnboardingScreen.kt
gradle/libs.versions.toml

Updates core to use the new onboarding and uses the new exposed methods.
Also fixes the wrong color of the current animation and of the status bar icons when system theme changes.
Depends on https://github.com/Infomaniak/android-core/pull/489

feat: Update onboarding

---

.github/workflows/translations-validation.yml

Adds translation validation using the Ink CLI. The workflow lists all android modules that need to verify their strings. This means that when we will create new modules in the futur, we'll have to think about updating this workflow to also check the new modules

feat: Add translations validation code based on ink
