Infomaniak/android-SwissTransfer

app/build.gradle.kts
app/src/main/AndroidManifest.xml
app/src/main/java/com/infomaniak/swisstransfer/ui/MainScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/navigation/NavigationArgs.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/navigation/NavigationItem.kt
app/src/main/res/values/strings.xml
gradle/libs.versions.toml

[i01] core: Navigation

---

app/src/main/java/com/infomaniak/swisstransfer/ui/theme/Shapes.kt

This PR tries to add basic values for radiuses across the app.
From a quick look at the specs, this seems to be the commonly used values. Mainly 16dp and 50%, but there also are some rare occurrences of 4dp and 8dp.
Depends on #10

Add shapes for the corner radiuses

---

app/src/main/java/com/infomaniak/swisstransfer/ui/navigation/NavigationDestination.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/components/AppNavigationSuiteScaffold.kt

After customizing `NavigationSuiteScaffold`, the navigation suite is no longer hidden when necessary

Fix adaptative navigation

---

app/src/main/java/com/infomaniak/swisstransfer/ui/components/MainScreenFab.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/NewTransferFab.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwissTransferFab.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/icons/app/Add.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/MainNavHost.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/components/AppNavigationSuiteScaffold.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/received/ReceivedScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/sent/SentScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/sent/SentViewModel.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/utils/ContextExt.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

Adds the fab in the main screen so it is displayed when needed and navigates to the new transfer activity.
The black arrow pointing to the fab is missing and will be added in a futur PR. 
Depends on #17

Add fab to the sent main screens

---

app/src/main/java/com/infomaniak/swisstransfer/ui/NewTransferActivity.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/BottomStickyButtonScaffold.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/ButtonType.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/DoubleButtonCombo.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/LargeButton.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwissTransferTobAppBar.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/theme/ColorDark.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/theme/ColorLight.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/theme/Theme.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

This way we will always create the screens the same way.
This PR also adds the LargeButton component but later on this LargeButton should be defined with the more normal buttons which share a bunch of characteristics as well

Add a scaffold for all the screens that use a top app bar + sticky buttons at the bottom of the screen and some LargeButton component

---

app/src/main/java/com/infomaniak/swisstransfer/ui/components/LargeButton.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwissTransferBottomSheet.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/theme/ColorDark.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/theme/ColorLight.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/theme/Shapes.kt

Actual usage of the bottom sheet for the new transfer screen comes in the next PR

Create a swiss transfer bottom sheet component for all bottoms sheets of the app

---

app/src/main/java/com/infomaniak/swisstransfer/ui/components/BrandTobAppBar.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwissTransferTobAppBar.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/icons/app/ArrowLeft.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/icons/app/Cross.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/icons/illu/LogoInfomaniak.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/icons/illu/LogoSwissTransfer.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/NewTransferNavHost.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/TransferTypeScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/theme/ColorDark.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/theme/ColorLight.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/theme/Theme.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

Add two components, one that displays the brand and one for when there's an actual title and icons. This top app bar makes it easy to add new icons and easy to reuse the common close and back icons as actions while preventing from forgetting to use a contentDescription.

Add the top app bar components

---

app/src/main/java/com/infomaniak/swisstransfer/ui/components/Buttons.kt

Adds the required missing small buttons (used in places like dialogs). They're built the exact same way as LargeButtons but we expose a different component for ease of use

Add small buttons components

---

app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsDurationValidityScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/components/SingleSelectOptions.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

depends on https://github.com/Infomaniak/android-SwissTransfer/pull/30

Implement validity period screen

---

app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwissTransferTobAppBar.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/components/OptionScaffold.kt

Fixes the text style of the SwissTransferTobAppBar and the disappearing back arrow when navigating back from the settings
Depends on #66

Fix top app bar

---

app/src/main/java/com/infomaniak/swisstransfer/ui/components/EmptyState.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/received/components/ReceivedEmptyFab.kt

Use stringResource instead of accessing getString through a context manually

---

app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/received/ReceivedScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/received/components/ReceivedEmptyFab.kt

Hide discovery message when transfer list has at least one item

---

app/src/main/java/com/infomaniak/swisstransfer/ui/components/TwoPaneScaffold.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/MainNavHost.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/MainScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/components/MainScaffold.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/components/PhoneTopAppBarScaffold.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/sent/SentScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsScreenWrapper.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/theme/Theme.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/utils/WindowAdaptativeInfoExt.kt

core: Pooling all adaptive tablet logic

---

app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/components/BrandTopAppBarScaffold.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/components/SmallWindowTopAppBarScaffold.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/received/ReceivedScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/sent/SentEmptyScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/sent/SentListScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/sent/SentScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/components/OptionScaffold.kt

Avoid passing the content padding through too many files when we don't need to. The freedom to handle the contentPaddings manually everywhere down the line is not needed.
Depends on #78

Simplify contentPadding usage

---

app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/NewTransferViewModel.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/TransferFile.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/TransferFileUtils.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/TransferFilesManager.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/UploadSourceChoiceBottomSheet.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/utils/FileNameUtils.kt
app/src/test/java/com/infomaniak/swisstransfer/PostifxedFileNameUnitTest.kt

Is missing:
* The selection of a folder
* The handling of subfolders
* The UI to display selected folders
* A way to remove files from the list of selected files

Add basic file picker logic backbone to new transfers

---

app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/LogoInfomaniak.kt

Removed XML optimizations to prevent the logo from being broken on API 30 or 31. 
API 33+ did not have the issue for sure, I did not test all the in between API levels though

Fix infomaniak logo on low api

---

app/src/main/java/com/infomaniak/swisstransfer/ui/components/DoubleButtonCombo.kt

The button wasn't properly constrained to half the width limit when the screen is large enough. This PR fixes the issue

Fix width of double button where only one button is defined

---

app/src/main/java/com/infomaniak/swisstransfer/ui/components/FileItem.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/FileItemList.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/SmallFileItem.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/previewparameter/FileUiListPreviewParameterProvider.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/components/ImportedFilesCard.kt

I was always using the same list of FileUiItems so instead of copy pasting it everywhere, I used the PreviewParameter that serves this very purpose
Depends on #87

Use a PreviewParameter to factorize FileUiItem instantiation inside previews

---

app/src/main/java/com/infomaniak/swisstransfer/ui/components/FileItem.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/FileItemList.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/FilePreview.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/SmallFileItem.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/previewparameter/FileUiListPreviewParameterProvider.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/received/ReceivedScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/sent/SentListScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/NewTransferViewModel.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/TransferFilesManager.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/components/ImportedFilesCard.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/utils/FileUiItemExt.kt

This only turns FileUiItem from an interface into a data class and renames it into FileUi
Depends on #88

Turn FileUiItem from interface to data class to make future replacement easier

---

app/build.gradle.kts
app/src/main/java/com/infomaniak/swisstransfer/ui/components/QrCode.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/qrInfomaniak/QrInfomaniak.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/qrInfomaniak/QrInfomaniakDark.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/qrInfomaniak/QrInfomaniakLight.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/theme/ColorDark.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/theme/ColorLight.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/theme/Theme.kt
gradle/libs.versions.toml

feat: Add QR Code in UploadSuccess screens

---

app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/ImportationFilesManager.kt

Files were kept from one startActivity to the other because the manager that help the files was a singleton instead of being reinstanciated every time the view model is reinstanciated

Fix lifecycle of imported files in new transfer

---

Core2/src/main/java/com/infomaniak/core2/DateUtils.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/FileItem.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/FileItemList.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwissTransferTopAppBar.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/TwoPaneScaffold.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/transfer/TransferFilePreview.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/transfer/TransferItem.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/transfer/TransferItemList.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/ArrowDownBar.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/FileZip.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/Share.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/received/ReceivedScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/received/ReceivedScreenWrapper.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/sent/SentListScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/sent/SentViewModel.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsScreenWrapper.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/components/OptionScaffold.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/TransferDetailsScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/TransferDetailsViewModel.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/components/TransferInfo.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/theme/ColorDark.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/theme/ColorLight.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/theme/Theme.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

Depends on #129
The quality gate failure about duplicated code can be ignored, it's only about testing code.

feat: Add TransferDetails screen

---

app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/ImportFilesViewModel.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt

The new name matches its usage better and follows the other view models naming as well

Rename NewTransferViewModel into ImportFilesViewModel

---

app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/components/TransferTypeButton.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/components/TransferTypeButtons.kt

The spacing was defined at multiple levels in order to have a specific amount of spacing when summing them all. This spacing at the end was too big compared to what we will want to have by the end for the design and it was defined to deeply inside the component.
Now the component doesn't specify any form of paddings and lets its parent handle this matter altogether

Fix transfert type button's spacing

---

app/src/main/java/com/infomaniak/swisstransfer/ui/components/HighlightedText.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/HighlighterText.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwissTransferTextField.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/components/AdHeader.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/theme/ColorDark.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/theme/ColorLight.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/theme/Theme.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

The upload progress screen has a "highlighter" styled bit of text. This highlighter style will also be present in the onboarding screens. In this PR, I created a `HighlighterText` component to display text with one part being highlighted and used it for the upload progress screen.

Add highlighted text in the title to the upload progress screen

---

app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwissTransferAlertDialog.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwissTransferTextField.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsViewModel.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/ImportFilesViewModel.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/TransferOptionsBottomSheets.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/components/PasswordOptionAlertDialog.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/components/WeightOneSpacer.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml
gradle/libs.versions.toml

Depends on #144 
Add the password option that was left out of the #144 PR

feat: Add password popup

---

app/src/main/java/com/infomaniak/swisstransfer/ui/components/QrCode.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/navigation/NavigationDestination.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/TransferDetailsScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/NewTransferNavHost.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadProgressScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadSuccessQrScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadSuccessScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/workers/UploadWorker.kt

refactor: Rename `transferLink` into `transferUrl`

---

app/src/main/java/com/infomaniak/swisstransfer/ui/previewparameter/EmailsPreviewParameterProvider.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadSuccessEmailScreen.kt

refactor: Extract usage of Emails test data

---

app/src/main/java/com/infomaniak/swisstransfer/ui/components/transfer/TransferItemList.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/transfer/TransfersListWithExpiredBottomSheet.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/MainNavHost.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/received/ReceivedScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/sent/SentScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transfers/TransfersScreenWrapper.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transfers/TransfersViewModel.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

feat: Make Sent screen use the ScreenWrapper

---

app/src/main/java/com/infomaniak/swisstransfer/ui/components/DoubleButtonCombo.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadSuccessQrScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/components/ShareAndCopyButtons.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/theme/Dimens.kt

The old design with 3 buttons on top of one another has been scrapped for a design with two bigger buttons but side by side this time around

Update share and copy link button's design

---

app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadProgressScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadProgressViewModel.kt
app/src/main/java/com/infomaniak/swisstransfer/workers/UploadWorker.kt

When the worker returned a Failure, it previously displayed the default ui state but a worker failure should display the upload error as the upload has stopped for good

Display upload error screen when worker fails

---

app/src/main/java/com/infomaniak/swisstransfer/ui/components/transfer/TransferItemList.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/transfer/TransfersListWithExpiredBottomSheet.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/received/ReceivedScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/sent/SentScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/TransferDetailsScreen.kt

feat: Use real data for Sent & Received transfers lists

---

app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/ImportFilesViewModel.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt

feat: Add transfer message

---

app/src/main/java/com/infomaniak/swisstransfer/ui/components/FileItem.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/FilePreview.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/SmallFileItem.kt

When importing a file during a new transfer we display SmallFileItem with the size LARGE. In this situation we want to display the first letters of the name so we can differentiate better files of the same filetype

Add filename to SmallFileItem for LARGE size

---

app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/components/Progress.kt

Instead of defining it 5 times

Centralize Progress text style

---

app/src/main/java/com/infomaniak/swisstransfer/ui/MainActivity.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/NewTransferActivity.kt

The different screens should be tracked when they're navigated to but tracking the activities doesn't provide any meaningful info

Stop tracking activities in Matomo

---

app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadProgressViewModel.kt
app/src/main/java/com/infomaniak/swisstransfer/workers/UploadWorker.kt

When the connection is lost, the worker goes into `enqueud` and receives the `Default` state, but the `Default` state does not contain the old `uploadedSize` data.

fix: Resume network with old uploaded size

---

app/src/main/java/com/infomaniak/swisstransfer/ui/images/icons/SignalCrossed.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/NewTransferNavHost.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadProgressScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadProgressViewModel.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/components/NetworkUnavailable.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/components/Progress.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/theme/ColorDark.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/theme/ColorLight.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/theme/Theme.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

Depends on #196
Depends on #199

feat: Add network status info when uploading a Transfer

---

app/src/main/java/com/infomaniak/swisstransfer/ui/components/Buttons.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/GenericButton.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwissTransferButton.kt

I need more control over the button to animate it properly in the onboarding screen of the app. This required me to extract a basic button that can be controlled more precisely than usually needed. 
This PR only abstracts this basic button in its own component and adapts the current buttons so they are defined on top of this basic button.
The only code that changed inside the definition of GenericButton compared to what was there previously can be seen in the first commit of the PR. It's the content of the button that became generic and the definition of the height of the button is not linked to ButtonSize at this level anymore

feat: Add a generic button component

---

app/src/main/java/com/infomaniak/swisstransfer/ui/components/HighlightedText.kt

Fix two issues when the argument of a HighlighterText are the last characters of the whole string. This PR also refactors the code to make it easier to understand because things were not named very clearly. The refactor and the fixes are visible in different commits.
---
Details of the bugs:
The range passed as argument to getBoundingBoxesForRange should stop at the last index of the string to not crash with an out of bound exception.
Also, the right coordinate of the each returned bounding box should be defined based on the current bounding box's last character's rect. This wasn't properly handled when the last character of the current bounding box was in any line but the last one of the whole string vs when it was at the end of the whole string

fix: HighlighterText's text when the argument is the last characters of the whole string

---

app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transfers/TransfersScreenWrapper.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

feat: Improve empty screen when we don't select a transfer

---

app/src/main/java/com/infomaniak/swisstransfer/ui/components/transfer/TransferExpiredBottomSheet.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/transfer/TransfersListWithExpiredBottomSheet.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/received/ReceivedScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/sent/SentScreen.kt

feat: The Delete button in the Expired bottomSheet is now functional

---

app/src/main/java/com/infomaniak/swisstransfer/ui/components/EmptyState.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/IllustratedMessageBlock.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/received/ReceivedScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/sent/SentScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsScreenWrapper.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transfers/TransfersScreenWrapper.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

https://github.com/user-attachments/assets/3f87d574-415e-4ea0-9a73-03b20a6b390b

feat: Update empty screen for sent, received transfers and settings screen

---

app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsScreen.kt

Dark theme is available since API 29: https://developer.android.com/develop/ui/views/theming/darktheme
- Left -> API 35
- Right -> API 28

feat: Hide theme in settings if device is running on API below 29

---

app/src/main/java/com/infomaniak/swisstransfer/ui/components/BottomStickyButtonScaffold.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/Buttons.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/DoubleButtonCombo.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwissTransferAlertDialog.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwissTransferBottomSheet.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/transfer/TransferExpiredBottomSheet.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/components/PasswordBottomSheet.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/components/QrCodeBottomSheet.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadErrorScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadProgressScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadSuccessEmailScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadSuccessQrScreen.kt

I need to pass a whole string and not a string res in a futur PR so I changed the signature of the buttons to make them more reusable. This also matches the type of signatures that material exposes already

feat: Replace titleRes with actual string titles in buttons

---

app/src/main/java/com/infomaniak/swisstransfer/ui/components/SmallFileItem.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/components/ImportedFilesCard.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/components/TransferOptionsTypes.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/components/TransferTypeButton.kt

The modifications are the following:
Remove the cross button from little files preview
Move the transfer type choice to the top of the screen
Make the whole file choice card clickable to go to the file details
Adjust the transfer type button's corner radius to match the text field's one
Hide the email language setting when email transfer type is not selected
Is missing:
Update the order of transfer option type according to the new ordering in the KMP library
Animation when email language advanced settings hides/appears

feat: Update import screen design

---

app/src/main/java/com/infomaniak/swisstransfer/ui/components/transfer/TransferItemList.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/transfer/TransfersListWithExpiredBottomSheet.kt

There was some padding stopping the list from ever reaching the vertical edges of the lazy column, I removed it.

fix: Make transfer lists stop only at the very edge of the lazy column

---

app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/TransferSendManager.kt

I'll later need to call two different logics with an integrity token so I refactored the code to be able to easily reuse the integrity token for any purpose

feat: Split app integrity logic from send transfer logic

---

app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/ImportFilesViewModel.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/TransferSendManager.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt

Was required to use the code in multiple screens
Depends on #278

feat: Merge send transfer states

---

app/src/main/java/com/infomaniak/swisstransfer/ui/navigation/NavigationDestination.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/ImportFilesViewModel.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/NewTransferNavHost.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadSuccessEmailScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadSuccessScreen.kt

feat: Require recipients and display real data to success screen

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/infomaniak/swisstransfer/ui/LaunchActivity.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/MainActivity.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/MainNavHost.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/MainScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/utils/DeeplinkExt.kt

- feat: Deeplink without Onboarding when the user is not connected
- fix: Even deeplink we can go to SentScreen destination

feat: Deeplink even unauthenticated

---

app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadSuccessQrScreen.kt

The spacing between the ShareAndCopy buttons and the "finish" button wasn't coherent with the usually stacked buttons and with the spec. I fixed it

fix: ShareAndCopy spacing

---

app/src/main/java/com/infomaniak/swisstransfer/ui/components/Buttons.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwissTransferAlertDialog.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwissTransferBottomSheet.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwissTransferButton.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/TransferDetailsScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/components/PasswordBottomSheet.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/NewTransferNavHost.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/NewTransferScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/components/PasswordOptionAlertDialog.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadErrorScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadProgressScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadSuccessQrScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/components/ShareAndCopyButtons.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/validateemail/components/ResendCodeCountDownButton.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

Don't let them escape!
This required me to refactor the dialog composable we already have to have greater control over the buttons. I opted for a more standard interfacing logic instead of adding a *lot* of parameters. We can now compose the dialog with buttons. There's still two constant buttons already defined for the standard cases.
This PR also required to add stacking buttons in dialogs when the buttons are too wide which required to change the design of the buttons for plain text buttons like the native material theme so they are not misaligned when stacked.
Depends on #254

feat: Add confirmation when trying to leave the new transfer flow

---

app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/received/ReceivedScreen.kt

The arrow and the message should only be displayed when you've zero items in "Sent"

feat: Hide the arrow message from "sent" screen about being your first transfer when it's not

---

Core2/Matomo/build.gradle.kts
Core2/Matomo/src/main/java/com/infomaniak/core2/matomo/Matomo.kt
app/build.gradle.kts
app/src/main/java/com/infomaniak/swisstransfer/ui/MainApplication.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/MatomoSwissTransfer.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsDataManagementMatomoScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsDataManagementSentryScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsMatomoViewModel.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsSentryViewModel.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/utils/DataManagementPreferences.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/utils/DataStoreUtils.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/utils/DataStoreValue.kt
gradle/libs.versions.toml

I store the matomo/sentry opt out state in a data store and read that value to prevent sending matomo/sentry events if the user has opted out.
To do this while centralizing the definition of data store's entries I had to add a few helper methods.
I also removed `NetworkException`s from Sentry the same way we did it on mail.

feat: Opt-out of Matomo & Sentry

---

app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwissTransferButton.kt

We decided to show loading buttons as if they were still enabled visually even though they can't be clicked anymore. This PR does just this and also fixes the color of the invisible loaders

feat: Update the button loader colors and stop showing them as disabled

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/infomaniak/swisstransfer/ui/LaunchActivity.kt

Make the launchActivity SingleTask to fix a bug where opening the app with a deeplink prevent us from reopening this deeplink after
Also clear the stack so the deeplinks aren't piling up in the stacks

fix: Avoid having the deeplinks piling in the stacks

---

app/src/main/java/com/infomaniak/swisstransfer/ui/components/NewTransferFab.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwissTransferTextField.kt

After discussing with the designer, he gave a few quick first feedbacks:
* The fabs should always have 0 elevation (received screen empty state or bottom right of the screen)
* Take this opportunity to remove the now useless HAND_RAIL value
* The textfields label and text should have the same font size. Right now, the label was at 16sp and the text was at 14sp. For now, he chose to use the native, default 16sp size of text and will check if other texts on the screen need to change later on

feat: Quick UI fixes

---

app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/ImportFilesViewModel.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt

Starting an upload and canceling it brings you back to the ImportFilesScreen. When doing so, the code would trigger and open the file picker again which we don't want.
Using a channel, we make sure the file picker event is only consumed once

feat: Prevent file picker from opening when backing after a canceled transfer

---

app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/settings/SettingsScreenWrapper.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

The string userfeedback thread will be the same for Android and iOS unlike the mail ones. It is expected that the URLs that currently link to the web userfeedback threads will be updated in the future to link to threads specific to mobile instead

chore: Update urlUserReportAndroid string key into urlUserReport

---

app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/filesdetails/NewTransferFilesDetailsScreen.kt

The ImportedFilesCard shows the latest files first but the TransferDetailsScreen was showing the earliest files first. This modifies the ordering of the data passed to the TransferDetailsScreen in order to match the "latest files first" logic of the ImportedFilesCard

fix: Use coherent ordering of files when importing files

---

app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/ImportFilesViewModel.kt

Right now the isFirstViewModelCreation is never set to true because the code above it suspends forever and we can never reach the line that set isFirstViewModelCreation to true. This modification makes the suspend code async in order to reach the place where isFirstViewModelCreation is set to true

fix: Set isFirstViewModelCreation to true

---

app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/components/EmailAddressTextField.kt

When the EmailTextField loses focus, or the user close the keyboard, we automatically check the field's value to add the email to the list

feat: Email text field auto add email when leaving field

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/infomaniak/swisstransfer/ui/LaunchActivity.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/NewTransferActivity.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/NewTransferNavHost.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/NewTransferScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadErrorScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/workers/UploadWorker.kt

Clear task when NewTransferActivity is the root of the task and make sure that the NewTransferActivity can't be stacked multiple times if files are shared to it

fix: Handle NewTransferActivity task correctly with the sharing of files

---

app/src/main/java/com/infomaniak/swisstransfer/ui/components/SwipeToDismissComponent.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/transfer/TransferItemList.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/components/transfer/TransfersListWithExpiredBottomSheet.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/received/ReceivedScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/sent/SentScreen.kt

When adding or removing items from the list of transfers it was instantaneous and was not animated. This PR adds animations when a new transfer is added or swiped away from the list

feat: Animate transfers in transfer lists

---

app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadProgressScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadProgressViewModel.kt

This only occurs if something very unexpected happens, but at least we should let the user leave even if we failed canceling the upload in progress properly.
When the app integrity check will be placed on the upload progress screen, this will also happen when we haven't received a container id from the API yet. If we want to cancel the upload during the API integrity this will also occur

feat: Let the user leave if we can't cancel the upload successfully

---

app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/NewTransferNavHost.kt

Clicking on the back arrow of the files details screen while the screen is animated as the screen leave the composition lets us back twice in a row. Doing so brings us to some strange empty white screen.
By calling navigateUp instead, the issue is no more

fix: Fix double click leading to empty white screen

---

app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadProgressViewModel.kt

No point in logging it to sentry and it should really should avoid calling onFailedCancellation()

fix: CancellationException being reported to sentry and triggering onFailedCancellation()

---

app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/ImportationFilesManager.kt

Read file size directly from the copied local io File instead of the content: Uri to avoid any possible errors in size caused by the content provider. This is an issue that supposedly can happen. 
Also adds a few breadcrumbs in case we need to track down the size of different files if another issue occurs

feat: Reduce probability of wrong file sizes when importing them in a new transfer

---

app/src/main/java/com/infomaniak/swisstransfer/ui/LaunchActivity.kt

If the user is logged out and shares files to the app, we won't find any AppSettings in Realm because they're initialized to an empty value during the login step.
A user will be logged out if the app received an intent before the user ever finished the onboarding. In case of such intent, we want to handle it correctly but we first need to connect the user seamlessly to avoid badly configured app settings

fix: Missing AppSettings in NewTransferActivity when sharing files to the app before user login

---

app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/filesdetails/NewTransferFilesDetailsScreen.kt

fix: Keep same display logic in transfer details screen

---

app/build.gradle.kts

`defaultConfig.versionCode` was previously overwritten, so we're using the `androidComponents` variants API to avoid the problem.

fix: Fix the release versionCode

---

app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/TransferDetailsScreen.kt

This is certainly what caused the download button to not update on tablets (mater/details UI) when selecting another transfer in the list.

fix: Fix transfer change not taken into account

---

app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/ImportFilesViewModel.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/ImportLocalStorage.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/ImportationFilesManager.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/SendButtonStatus.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/TransferCountChannel.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt

The file progress when importing is now continuous because it counts the copied bytes instead of couting the number of copied files which is very limited to visually indicate the progress

feat: Define the file import progress as amount bytes instead of amount of files

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/infomaniak/swisstransfer/ui/components/FilePreview.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/components/MainScaffold.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/components/Progress.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/validateemail/ValidateUserEmailScreen.kt
build.gradle.kts

This is safe to do since all the APIs we use in Compose should already handle configChanges.
I made sure that `Context` objects are used as a remember keys when applicable.

chore: Declare handled config changes

---

app/src/main/java/com/infomaniak/swisstransfer/ui/NewTransferActivity.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/appIntegrity/GhostScrollCrossPointing.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/appIntegrity/GhostScrollCrossPointingDark.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/images/illus/appIntegrity/GhostScrollCrossPointingLight.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/navigation/NavigationDestination.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/ImportFilesViewModel.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/NewTransferNavHost.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/SendButtonStatus.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/TransferSendManager.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadIntegrityErrorScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadProgressScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadProgressViewModel.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/components/Progress.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/validateemail/ValidateUserEmailScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/validateemail/ValidateUserEmailViewModel.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/utils/UploadSessionExt.kt
app/src/main/java/com/infomaniak/swisstransfer/workers/UploadWorker.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

The idea is that the app integrity is now done while on the upload progress screen. This required to move all of the handling of success/errors of the app integrity and container creation from the `ImportFilesScreen` to the `UploadProgressScreen`.
The navigation has been modified to acomodate for the new order of screens. This implies amongst other things that `ValidateUserEmailDestination` is now accessible after `UploadProgressScreen` which required me to pass the `authorEmail` used by `ValidateUserEmailDestination` through `UploadProgressScreen`.
The sending of a transfer is now unified inside the same entry point `sendLastTransfer()` which fetches the last upload session from realm. The logic when sending a new transfer is the following: generate a new upload session, store it in …

feat: Move integrity token call to the upload progress screen

---

app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/TransferDownloadComposeUi.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/theme/ColorDark.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/theme/ColorLight.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/theme/Theme.kt

fix: Add background for button describing the download status of a file and display the check icon when the file has been downloaded

---

app/src/main/java/com/infomaniak/swisstransfer/ui/LaunchActivity.kt

This will avoid the SecurityExceptions we're getting upon importing files that takes place after
the LaunchActivity is destroyed following
our call to finish().

fix: Forward Uri read permission from LaunchActivity to NewTransferActivity

---

app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/received/ReceivedScreen.kt

The illustration should've been the one with the ghost looking through binoculars not the one with a magnifying glass

fix: Use correct illustration for empty state of received screen

---

app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/pickfiles/PickFilesScreen.kt

Notifications are optional when uploading a file.

fix: Don’t block upload if notification permission is denied

---

app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/TransferDownloadComposeUi.kt

The floating point conversion was done too late.

fix: Fix display of download progress

---

app/src/main/java/com/infomaniak/swisstransfer/upload/InputStreamContent.kt
app/src/main/java/com/infomaniak/swisstransfer/upload/TransferUploader.kt
app/src/main/java/com/infomaniak/swisstransfer/upload/UriToOutgoingContent.kt
app/src/main/java/com/infomaniak/swisstransfer/workers/FileChunkSizeManager.kt
gradle/libs.versions.toml

This PR reduces the memory consumption dramatically (first commit), and implements automatic retries (second commit).
It also simplifies the logic that we used to ensure that the last chunk was sent only after all the previous ones were sent.
Depends on https://github.com/Infomaniak/android-core/pull/324
Depends on https://github.com/Infomaniak/multiplatform-SwissTransfer/pull/200
Also requires a version of the KMP module to be released.

feat: Auto retries + streamed upload

---

app/src/main/java/com/infomaniak/swisstransfer/upload/UploadForegroundService.kt

This might fix some ForegroundServiceStartNotAllowedException issues.

chore: Prevent UploadForegroundService from being restarted by the OS

---

app/src/main/java/com/infomaniak/swisstransfer/di/CrashReportImpl.kt
app/src/main/java/com/infomaniak/swisstransfer/di/SwissTransferInjectionModule.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/AlreadyUsedFileNamesSet.kt
gradle/libs.versions.toml

This PR hooks the new error reporting interface with the existing Sentry instance.
Depends on https://github.com/Infomaniak/multiplatform-SwissTransfer/pull/202
iOS sister PR https://github.com/Infomaniak/ios-SwissTransfer/pull/216

feat(Sentry): Hook KMP error interface with Sentry

---

build.gradle.kts

This allows the project to use Kotlin 2.1+ safely.

chore: Improve Gradle plugins version management

---

app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/received/TransferExpiredDownloadCreditScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/TransferDetailsScreen.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transferdetails/TransferDetailsViewModel.kt
app/src/main/java/com/infomaniak/swisstransfer/ui/screen/main/transfers/TransfersScreenWrapper.kt

~~A general purpose string is missing for an expired transfer.~~
~~Depends on https://github.com/Infomaniak/multiplatform-SwissTransfer/pull/178~~

fix: Display an error screen when coming from a deeplink and transfer is null

---

app/src/main/java/com/infomaniak/swisstransfer/ui/screen/onboarding/OnboardingScreen.kt

BackHandler got factorized inside of OnboardingScaffold and the way to compute onboardingPages was overkill

chore: Update onboarding with new core
